- name: Packages | Pacman Base Packages Install
  become: true
  tags: arch,package
  pacman:
    name: 
    # zsh + stuff needed for plugins
      - zsh
      - zoxide
      - otf-firamono-nerd
      - fzf
      - fastfetch
    # Terminal Editors
      - nano
      - vim
      - neovim
      - vi #for visudo could remove later
    # Extra stuff for now
      - python
      - htop
      - cmatrix 
  
  # tmux
# fonts
# tailscale?
    