- name: Packages | Pacman Base Packages Install
  become: true
  tags: arch,package
  pacman:
    name: 
    # zsh + stuff needed for plugins
      - zsh
      - zoxide
      - otf-firamono-nerd
      - fzf
      - fastfetch
      - eza
    # Terminal Editors
      - nano
      - vim
      - neovim
      - vi #for visudo could remove later
      - less
      - bat
      - superfile
      - git
    # Extra stuff for now
      - python
      - htop
      - btop
      - cmatrix
      - tldr
      - tailscale
# tmux
# fonts